service: whatsapp-webhooks
frameworkVersion: '3'

provider:
 name: aws
 runtime: nodejs14.x
 lambdaHashingVersion: 20201221
 environment:
  TOKEN: ${env:APP_TOKEN}

plugins:
 - serverless-offline
 - serverless-plugin-include-dependencies

functions:
 app:
   handler: handler.handler
   events:
     - http: ANY /
     - http: 'ANY {proxy+}'